config/routes.rb
Jqclient::Application.routes.draw do
  resources :login_histories

  post "users/sign_in"
  
  match 'users/sign_in' ,:to => 'contacts#index', :via => 'get'
  get "users/sign_out"

  get 'contacts/vendors'
  get 'contacts/landlords'

  resources :contacts do
    collection do 
      post 'search'
    end
    member do 
      get 'add_note' 
      post 'add_note'
    end
      
  end
  match '/token'  => 'contacts#token', via: 'get'
  

   root :to => 'high_voltage/pages#show', :id => 'index'

end

app/models/contact.rb
class Contact < ActiveResource::Base
  #include HTTParty
  #base_uri Rails.configuration.idashboard_url + '/api'
  UNAUTHORIZED = "Unauthorized"
  self.site = Rails.configuration.idashboard_url
  self.prefix = "/api/"
  self.element_name = 'contact'
  self.collection_name = 'contacts'
  self.include_root_in_json = true
  #self.format = :json
  @@token = nil
  attr_accessor :contact_attribute_ids
  attr_accessor :phone_numbers_attributes
  
  cattr_accessor :static_headers
  self.static_headers = headers
  
  def self.headers
    new_headers = static_headers.clone
    new_headers['authorization'] = "Bearer #{token}"
    new_headers
  end
  
  def self.token=(arg)
    @@token = arg 
  end
  
  def self.token 
    @@token
  end
  
  def token
    @@token
  end
  
  def self.categories
    
    conn = Faraday.new(:url => Rails.configuration.idashboard_url) 
      
    response = conn.get do |req|
      req.url '/api/contact_categories'
      req.headers['authorization'] = "Bearer #{token}" if token
    end
    
    json = JSON.parse(response.body)
    category_array = json['agency']['contact_categories']
    category_array.collect do |element|
      cat = element['contact_category']
      FunkyStruct.new(code: cat['code'], name: cat['name'] , id: cat['id'] )
    end
  end
  
  def add_note(text,author)
    params = { :contact => { :notes_attributes => [ {:note_body => text, :date_added => Time.now, :author => author} ]
      }
    }
    conn = Faraday.new(:url => Rails.configuration.idashboard_url) 
    
    response = conn.put do |req|
      req.url "/api/contacts/#{self.id}"
      req.headers['authorization'] = "Bearer #{token}" if token
      req.params = params
    end
    
    response.status == 200    
  end
  
  def notes
    notes_array = self.get(:notes)['contact_notes']  
    notes_array.collect do |element|
      note = element['contact_note']
      FunkyStruct.new(author: note['author'], note_body: note['note_body'], date_added: note['date_added'], id: note['id'])
    end
  end
  
  def phone_id
    if self.attributes['phone_numbers_attributes'].is_a?(Hash)
      self.attributes['phone_numbers_attributes']['id'] || "_new"
    else
      self.attributes['phone_numbers_attributes'].attributes.delete("id") || "_new"
    end
  end
  
  def phone_attributes
    if self.attributes['phone_numbers_attributes'].is_a?(Hash)
      self.attributes['phone_numbers_attributes']
    else
      self.attributes['phone_numbers_attributes'].attributes
    end
  end
  
  def to_my_params
    x = { 
      :contact => 
      {
        first_name: self.first_name, last_name: self.last_name, contact_attribute_ids: ([self.attributes['contact_attribute_ids']] || [nil]) , email: self.email,
        phone_numbers_attributes: { phone_id.to_s.to_sym  =>  phone_attributes }
       } 
    }
    puts "returning #{x}"
    x
  end
  
  def self.search(arg)
    conn = Faraday.new( :url => Rails.configuration.idashboard_url )
    response = conn.get do |req|
      req.url "/api/search_contacts"
      req.headers['authorization'] = "Bearer #{token}" if token
      req.params = {search: arg, per_page: "50"}
    end    
    if response.status == 200
      JSON.parse( response.body )['results']['contacts'].collect do |element|
        find( element['contact']['id'])
      end
    else
      raise UNAUTHORIZED
    end
  end
  
  def save
    self.new_record? ? faraday_create : faraday_update
  end
  
  def faraday_create
    puts "on faraday create"
    conn = Faraday.new(:url => Rails.configuration.idashboard_url)   
    response = conn.post do |req|
      req.url "/api/contacts"
      req.headers['authorization'] = "Bearer #{token}" if token
      req.params = self.to_my_params
    end
    if response.status == 201
      id = JSON.parse( response.body )['contact']['id']
      self.attributes = self.class.find(id).attributes
    end
    
  end
  
  def faraday_update()
    conn = Faraday.new(:url => Rails.configuration.idashboard_url)   
    response = conn.put do |req|
      req.url "/api/contacts/#{self.id}"
      req.headers['authorization'] = "Bearer #{token}" if token
      req.params = self.to_my_params
    end
    response.status == 200 ? true : (raise UNAUTHORIZED)
  end
    
end

class ActiveResource::Base
def self.instantiate_collection(collection, prefix_options = {})
          puts "instantiate collection from my patch..."
          collection = collection["contacts"]
      
          collection.collect! { |record| instantiate_record(record, prefix_options) }
 end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  before_filter :set_token, only: [:create,:update, :vendors, :landlords, :search, :add_note]
  before_filter :load_contact, only: [:edit,:update, :add_note]
  before_filter :check_auth, except: [:token]
  respond_to :html, :js
  #before_filter :require_premium, only: [:new, :edit, :add_note]
    
  #caches_action :landlords, :expires_in => 300.seconds, :unless_exist => true
  #caches_action :vendors, :expires_in => 300.seconds, :unless_exist => true
    
  def set_token
    Employee.token = session[:access_token]
  	Contact.token = session[:access_token]
    Requirement.token = session[:access_token]
    
    puts "setting token #{session[:access_token]}"
  end
  
  def load_contact
    @contact = Contact.find(params[:id])
  end
  
  def add_note
    if params['note']
      if !params['note'].blank? && @contact.add_note(params['note'], current_user.name)
       flash[:notice] = "Note added!" 
       redirect_to(:back)
      else 
       render status: 200
      end
    else
      render layout: false
    end
  end
  
  def search
    @contacts = params[:search].split.collect do |param| 
      Contact.search(param)
    end.flatten.uniq
    

    render partial: 'contact', collection: @contacts
      
    
  end
  
  def index

  end
  
  def new 
    phone_numbers_attributes = {name: nil, number: nil }
    @contact = Contact.new(first_name: nil, contact_attribute_ids: nil, last_name: nil, email: nil, phone_numbers_attributes: phone_numbers_attributes )
  end
  
  def edit
    @contact = Contact.find( params['id'] )
    puts "editing contact #{@contact.name}"
    render :layout => false
  end
  
  def update

    note = params["note"]
    @contact.attributes = params['contact']
    @contact.id = params['id']
    @contact.contact_attribute_ids = [params['contact']['contact_attribute_ids']]
    @contact.phone_numbers_attributes = params['contact']['phone_numbers_attributes']
    if @contact.save
      unless note.blank? 
        @contact.add_note(note,current_user.name)
      end 
      flash[:notice] = "Contact updated!"
      redirect_to :back
    else
      flash[:notice] = "problem updating the contact"
      redirect_to edit_contact_path(id: @contact.id)
    end
  end
  
  def vendors
    @page_name = "Vendors"
    @current_user_id = current_user.id
    @vendors_landlords = Rails.cache.fetch("#{current_user.id}_vendors", expires_in: 300.seconds) do
      current_user.vendors
    end
    respond_to do |format|
      format.html{ render "vendors_landlords" }
      format.js
    end
  end
  
  def landlords
    @page_name = "Landlords"
    @current_user_id = current_user.id
    @vendors_landlords =  Rails.cache.fetch("#{current_user.id}_landlords", expires_in: 300.seconds ) do
      current_user.landlords
    end
    respond_to do |format|
      format.html{ render "vendors_landlords" }
      format.js
    end
  end

  def create 
  	params['contact']['contact_attribute_ids'] = [ params['contact']['contact_attribute_ids']  ]
    note = params["note"]
    contact = Contact.new( params['contact'] )
  	if (contact.save)
      unless note.blank? 
        puts "adding a note"
        contact.add_note(note, current_user.name)
      end
      unless params['requirement']['name'].blank? 
        puts "creating requirement"
        params['requirement']['postal_area_names'] = [params['requirement']['postal_area_names'] ]
        requirement = Requirement.new(params['requirement'])
        requirement.prefix_options = {:contact_id => contact.id}
        requirement.save
      end
      puts "deu certo..."
  	  flash[:notice] = "#{contact.name} added to iDashboard!"
      flash.keep
  	  redirect_to page_path("menu")
    else
      flash[:notice] = "Notice: Last name is required."
      redirect_to "/contacts/new"
    end
  end

end

app/views/contacts/_contact.html.erb
<li class="swipeout">
  <div class="swipeout-content item-content">
    <div class="item-inner">
    	<a href="#" class="actions" data-name="<%= [contact.name,contact.company_name].reject(&:blank?).first %>" data-phone="<%= (!contact.mobile.strip.blank? rescue nil) ? contact.mobile : "Unknown" %>" data-contact="<%= contact.id %>" data-email="<%= contact.email %>">
      	<div class="item-title">
      		<%= [contact.name,contact.company_name].reject(&:blank?).first %>
					<br>
					<span><i class="i-phone"></i> <%= (!contact.mobile.strip.blank? rescue nil) ? contact.mobile : "Unknown" %></span>
				</div>
    	</a>
    </div><!-- item inner -->
  </div><!-- item content -->
  <!-- swipe to delete
  =================================== -->
  <div class="swipeout-actions">
    <div class="swipeout-actions-inner">
      <!-- Add this button and item will be deleted automatically -->
      <a href="#" data-confirm="Are you sure you want to delete this contact?"  class="swipeout-delete">Delete</a>
    </div>
  </div>
</li>

app/views/contacts/_form.html.erb
<!-- We don't need full layout here, because this page will be parsed with Ajax-->

<!-- NavBar 
**************************************** -->
<div class="navbar">
  <div class="navbar-inner">
    <div class="left sliding">
	    <!-- Right link contains only icon - additional "icon-only" class-->
      <a href="#" class="link icon-only open-panel"><i class="i-bars"></i></a>
    </div>
    <div class="center sliding"><%= @contact.name rescue nil || "New contact" %></div>
  </div>
</div>


<!-- Page 
**************************************** -->
<div class="pages navbar-through toolbar-through">
  <div data-page="add-contact" class="page page-add-contact">
  
    <div class="page-content">
		  <%= form_for(@contact, id: "demoform-1", html: { class: "list-block" }) do |form| %>
      	<div class="content-block-title">Contact Details</div>
        <ul>
        	<!-- Category
        	============================= -->
        	<li>
            <div class="item-content">
              <div class="item-inner">
                <div class="item-title label">Category</div>
                <div class="item-input">
                  <%= form.select(:contact_attribute_ids, contact_categories, :html => {:name => "contact[contact_attribute_ids][]"})%>
                </div>
              </div>
            </div>
          </li>
        	<!-- first name
        	============================= -->
        	<li>
            <div class="item-content">
              <div class="item-inner">
                <div class="item-title label">First name</div>
                <div class="item-input">
                  <%= form.text_field :first_name, placeholder: "Tap here to type" %>
                </div>
              </div>
            </div>
          </li>
          <!-- last name
        	============================= -->
          <li>
            <div class="item-content">
              <div class="item-inner">
                <div class="item-title label">Last name</div>
                <div class="item-input">
                  <%= form.text_field :last_name, placeholder: "Tap here to type" %>
                </div>
              </div>
            </div>
          </li>
          <!-- email
        	============================= -->
          <li>
            <div class="item-content">
              <div class="item-inner">
                <div class="item-title label">Email</div>
                <div class="item-input">
                  <%= form.text_field :email, placeholder: "Tap here to type", type: "email" %>
                </div>
              </div>
            </div>
          </li>
          <!-- Phone Type
        	============================= -->
        	<li>
            <div class="item-content">
              <div class="item-inner">
                <div class="item-title label">Phone type</div>
                <div class="item-input">
                  <%= select("contact[phone_numbers_attributes]", "name" , options_for_select( [ ["Mobile", "mobile"] , ["Home phone","home"], ["Work Phone","work"] ])) %>
                </div>
              </div>
            </div>
          </li>
          <!-- Phone number
        	============================= -->
          <li>
            <div class="item-content">
              <div class="item-inner">
                <div class="item-title label">Number</div>
                <div class="item-input">
                  <%= form.text_field "phone_numbers_attributes", placeholder: "Tap here to type", class: "phoneNumber", type: "number", name: "contact[phone_numbers_attributes][number]"%>
                </div>
              </div>
            </div>
          </li>
          <!-- Note
        	============================= -->
          <li class="align-top">
            <div class="item-content">
              <div class="item-inner">
                <div class="item-title label">Add a note</div>
                <div class="item-input">
                  <textarea name="note" placeholder="Tap here to type"></textarea>
                </div>
              </div>
            </div>
          </li>
        </ul>
        
        <div class="content-block-title">Requirements</div>
        <ul>
        	<!-- requirement name
        	============================= -->
        	<li>
            <div class="item-content">
              <div class="item-inner">
                <div class="item-title label">Name</div>
                <div class="item-input">
                  <input type="text" placeholder="Tap here to type" name="requirement[name]"/>
                </div>
              </div>
            </div>
          </li>
          <!-- Suburbs
        	============================= -->
        	<li>
            <div class="item-content">
              <div class="item-inner">
                <div class="item-title label">Suburbs</div>
                <div class="item-input">
                  <%= select( :requirement, "postal_area_names", suburbs_serviced, {prompt: ""}, {multiple: true} ) %>
                </div>
              </div>
            </div>
          </li>
          <!-- Looking to
        	============================= -->
        	<li>
            <div class="item-content">
              <div class="item-inner">
                <div class="item-title label">Looking to</div>
                <div class="item-input">
                  <select name="requirement[requirement_category]">
                    <option value="residential_sale">Buy</option>
                    <option value="residential_lease">Rent</option>
                  </select>
                </div>
              </div>
            </div>
          </li>
          <!-- Min Price
        	============================= -->
        	<li>
            <div class="item-content">
              <div class="item-inner">
                <div class="item-title label">Min Price</div>
                <div class="item-input">
                  <input type="number" placeholder="Tap here to type" name="requirement[min_price]"/>
                </div>
              </div>
            </div>
          </li>
          <!-- Max Price
        	============================= -->
        	<li>
            <div class="item-content">
              <div class="item-inner">
                <div class="item-title label">Max Price</div>
                <div class="item-input">
                  <input type="number" placeholder="Tap here to type" name="requirement[max_price]"/>
                </div>
              </div>
            </div>
          </li>
          <!-- Bedrooms
        	============================= -->
        	<li>
            <div class="item-content">
              <div class="item-inner">
                <div class="item-title label">Bedrooms</div>
                <div class="item-input">
                  <select name="requirement[min_bedrooms]">
                    <%= options_for_select( [ ["Any", nil] , ["1+", "1"], ["2+", "2"], ["3+", "3"], ["4+", "4"], ["5+", "5"] ])%>
                  </select>
                </div>
              </div>
            </div>
          </li>
          <!-- Bathrooms
        	============================= -->
        	<li>
            <div class="item-content">
              <div class="item-inner">
                <div class="item-title label">Bathrooms</div>
                <div class="item-input">
                  <select name="requirement[min_bathrooms]">
                    <%= options_for_select( [ ["Any", nil] , ["1+", "1"], ["2+", "2"], ["3+", "3"], ["4+", "4"], ["5+", "5"] ])%>
                  </select>
                </div>
              </div>
            </div>
          </li>
          <!-- Car Spaces
        	============================= -->
        	<li>
            <div class="item-content">
              <div class="item-inner">
                <div class="item-title label">Car Spaces</div>
                <div class="item-input">
                  <select name="requirement[min_car_parks]">
                    <%= options_for_select( [ ["Any", nil] , ["1+", "1"], ["2+", "2"], ["3+", "3"], ["4+", "4"], ["5+", "5"] ])%>
                  </select>
                </div>
              </div>
            </div>
          </li>
        </ul>
        
        <button type="submit"><%= @contact.new_record? ? "Create" : "Save" %></button>
     <% end %>
     
    </div><!-- page content -->
    
  </div><!-- page -->
</div><!-- pages -->

app/views/contacts/_nav_bar.html.erb
<ul class="navBar">
	<%= link_to contacts_vendors_path, remote: true do %>
    <li class="<%= @page_name == 'Vendors' ? 'active' : '' %>">
      <div class="inner">
        <i class="icon-user"></i>
        <p>Vendors</p>
      </div>
    </li>
	<% end %>
	
	<%= link_to contacts_landlords_path , remote: true  do %>
    <li class="<%= @page_name == 'Landlords' ? 'active' : '' %>">
      <div class="inner">
        <i class="icon-home"></i>
        <p>Landlords</p>
      </div>
    </li>
	<% end %>
	
  <a href="/contacts">
    <li class="<%= @page_name == 'Contacts' ? 'active' : '' %>">
      <div class="inner">
        <i class="icon-group"></i>
        <p>Contacts</p>
      </div>
    </li>
  </a>
  <a href="/contacts/new">
    <li>
      <div class="inner">
        <i class="icon-plus"></i>
        <p>Add</p>
      </div>
    </li>
  </a>
</ul>

app/views/contacts/_requirement_form.html.erb
    <div data-role="fieldcontain">
        <fieldset data-role="controlgroup">
            <label for="textinput10">
            </label>
            <input id="textinput10" name="requirement[name]" placeholder="Requirement name" value="" type="text" />
        </fieldset>
    </div>
		
		
    <div data-role="fieldcontain">
        <label for="">
        </label>
        
				<%= select( :requirement, "postal_area_names", suburbs_serviced, {:prompt => "Please select"}, {:multiple => true, "data-native-menu" => false, "data-iconpos" => "left", "data-icon" => "grid"} ) %>
				
    </div>
		
		
		
    <div data-role="fieldcontain">
        <label for="selectmenu2">
        </label>
        <select name="requirement[requirement_category]" id="selectmenu2" data-theme="a">
            <option value="residential_sale">
                Residential Sale
            </option>
            <option value="residential_lease">
                Residential Rent
            </option>
        </select>
    </div>
    <div data-role="fieldcontain">
        <label for="selectmenu3">
            Price
        </label>
        <select name="requirement_price" id="selectmenu3" data-theme="e">
            <option value="200000_400000">
                200k - 400k
            </option>
            <option value="400000_600000">
                400k - 600k
            </option>
            <option value="600000_800000">
                600K - 800k
            </option>
        </select>
    </div>
    <div data-role="fieldcontain">
        <label for="selectmenu4">
            Bedrooms
        </label>
        <select name="requirement[min_bedrooms]" id="selectmenu4" data-theme="b">
            <option value="1">
                1+
            </option>
            <option value="2">
                2+
            </option>
            <option value="3">
                3+
            </option>
            <option value="4">
                4+
            </option>
            <option value="5">
                5+
            </option>
        </select>
    </div>

    <div data-role="fieldcontain">
        <label for="bathrooms">
            Bathrooms
        </label>
        <select name="requirement[min_bathrooms]" id="bathrooms" data-theme="b">
            <option value="1">
                1+
            </option>
            <option value="2">
                2+
            </option>
            <option value="3">
                3+
            </option>
            <option value="4">
                4+
            </option>
            <option value="5">
                5+
            </option>
        </select>
    </div>

    <div data-role="fieldcontain">
        <label for="car_parks">
            Car parks
        </label>
        <select name="requirement[min_car_parks]" id="car_parks" data-theme="b">
            <option value="1">
                1+
            </option>
            <option value="2">
                2+
            </option>
            <option value="3">
                3+
            </option>
            <option value="4">
                4+
            </option>
            <option value="5">
                5+
            </option>
        </select>
    </div>

app/views/contacts/_vendors_landlords.html.erb
<!-- NavBar 
**************************************** -->
<div class="navbar">
  <div class="navbar-inner">
    <div class="left sliding">
	    <!-- Right link contains only icon - additional "icon-only" class-->
      <a href="#" class="link icon-only open-panel"><i class="i-bars"></i></a>
    </div>
    <div class="center sliding"><%= @page_name %></div>
  </div>
</div>


<!-- Page 
**************************************** -->
<div class="pages navbar-through toolbar-through">
  <div data-page="vendors" class="page">
  	<!-- Search Bar
    ======================================== -->
  	<form class="searchbar">
      <div class="searchbar-input">
        <input type="search" id="filter_contacts" placeholder="Filter"/><a href="#" class="searchbar-clear"></a>
      </div>
    </form>
    <div class="searchbar-overlay"></div>
  
    <div class="page-content contacts-content">
      
      <!-- Nothing Found Section
    	======================================== -->
    	<div class="list-block searchbar-not-found">
        <ul>
          <li class="item-content">
            <div class="item-inner">
              <div class="item-title">Nothing found</div>
            </div>
          </li>
        </ul>
      </div>
      <!-- Start List Block
    	======================================== -->
      <div class="list-block contacts-block search-here list-block-search searchbar-found">
        <div class="list-group">        
          
            <% current_letter = "" %>
            <% @vendors_landlords.sort_by{ |item| [item.contact['name'],item.contact['company_name']].reject(&:blank?).first.upcase }.each do |item| %>
              <% loop_letter = [ item.contact['name'],item.contact['company_name'] ].reject(&:blank?).first[0].upcase %>
              <% if current_letter != loop_letter  %>
                <ul class="filterable">
                  <% current_letter = loop_letter %>
                  <li class="list-group-title item-title"><%= current_letter %></li>
                  <%= render partial: 'vendors_landlords_item', collection: @vendors_landlords.select{ |item| [item.contact['name'],item.contact['company_name']].reject(&:blank?).first[0].upcase == loop_letter }, as: :item %>	
                </ul>
              <% end %>
            
            <% end %>
          
          </ul>
        </div><!-- list-group -->
      </div><!-- list block -->
    </div><!-- page content -->
  </div><!-- page -->
</div><!-- pages -->

app/views/contacts/_vendors_landlords_item.html.erb
<% contact_name = [item.contact["name"],item.contact["company_name"]].reject{|x| x.try(:strip).blank?}.first %>
<% contact_phone = !item.contact["mobile"].strip.blank? ? item.contact["mobile"] : "Unknown" %>
<% contact_id = item.contact['id'] %>

<li class="swipeout" >
  <div class="swipeout-content item-content">
    <div class="item-inner">
    	<a href="#" class="actions" data-name="<%= contact_name %>" data-phone="<%= contact_phone %>" data-contact="<%= contact_id %>" data-email="<%= item.contact['email'] %>">
      	<div class="item-title">
      		<%= contact_name %>
					<br>
					<span><i class="i-map-marker">  <%= item.listing["address"] %></i></span>
					<span><i class="i-phone"></i> <%= contact_phone %></span>
				</div>
    	</a>
    </div><!-- item inner -->
  </div><!-- item content -->
  <!-- swipe to delete
  =================================== -->
  <div class="swipeout-actions">
    <div class="swipeout-actions-inner">
      <!-- Add this button and item will be deleted automatically -->
      <a href="#" data-confirm="Are you sure you want to delete this contact?"  class="swipeout-delete">Delete</a>
    </div>
  </div>
</li>

app/views/contacts/add_note.html.erb
  <div class="view navbar-fixed">
    <div class="page">
      <div class="navbar">
        <div class="navbar-inner">
          <div class="center">Add a note</div>
          <div class="right"><a href="#" class="link close-popup">Done</a></div>
        </div>
      </div>
      <div class="page-content">
          <div class="content-block">
            <%= form_tag(add_note_contact_path(id: @contact.id), class: "store-data list-block" , id: "adding_note" , method: "POST"  ) do %>
              <ul class="note">
                <li class="align-top">
                  <div class="item-content">
                    <div class="item-inner">

                      <div class="item-input">
                        <textarea name="note" placeholder="Tap here to type"></textarea>
                      </div>
                    </div>
                  </div>
                </li>                
              </ul>
          	<% end %>
          </div>
        </div>
      </div>
    </div>

app/views/contacts/index.html.erb
  



 
<!-- We don't need full layout here, because this page will be parsed with Ajax-->

<!-- NavBar 
**************************************** -->
<div class="navbar">
 <div class="navbar-inner">
   <div class="left sliding">
    <!-- Right link contains only icon - additional "icon-only" class-->
     <a href="#" class="link icon-only open-panel"><i class="i-bars"></i></a>
   </div>
   <div class="center sliding">My Contacts</div>
 </div>
</div>


<!-- Page 
**************************************** -->

<div class="pages navbar-through toolbar-through">
 <div data-page="vendors" class="page page-contacts">
 	<!-- Search Bar
   ======================================== -->
 <form action="/contacts/search" method="post" data-search-list=".earch-here" data-search-in=".item-title" class="searchbar" id="contacts_search">
     <div class="searchbar-input">
       <input type="search" placeholder="Search" name="search" class="search_input"/>
       <a href="#" class="searchbar-clear"></a>
     </div>
     <button type="submit" class="searchbar-button">Search</button>
  </form>
   <div class="searchbar-overlay"></div>

   <div class="page-content contacts-content">
      <div class="list-block contacts-block search-here searchbar-found">
        <% if @contacts.blank? %>
         	<p>
         		<i class="i-search"></i>
         		<br>
         		Search for your contacts by typing<br>on the search box above.
         	</p>
        <% end %>
        
        <div class="list-group">
        
          <ul id="result_list">

          
          </ul>
        </div><!-- list-group -->
      </div><!-- list block -->    
   </div><!-- page content -->
  
 </div><!-- page -->
</div><!-- pages -->

app/views/contacts/landlords.js.erb
$('#main_div').html('<%= j render partial: "vendors_landlords"%>');
$('#show_loading').hide();
$('a[data-remote=true]').bind('ajax:beforeSend', function(){
  $('#show_loading').show();
});

app/views/contacts/new.html.erb
<%= render 'form' %>

app/views/contacts/vendors_landlords.html.erb
<%= render partial: "vendors_landlords" %>