config/routes.rb
Jqclient::Application.routes.draw do
  resources :login_histories

  post "users/sign_in"
  
  match 'users/sign_in' ,:to => 'contacts#index', :via => 'get'
  get "users/sign_out"

  get 'contacts/vendors'
  get 'contacts/landlords'

  resources :contacts do
    collection do 
      post 'search'
    end
    member do 
      get 'add_note' 
      post 'add_note'
    end
      
  end
  match '/token'  => 'contacts#token', via: 'get'
  

   root :to => 'high_voltage/pages#show', :id => 'index'

end

app/models/login_history.rb
class LoginHistory < ActiveRecord::Base
  attr_accessible :employee_id, :name, :login
  validates :login, presence: true
  validates :employee_id, presence: true
  belongs_to :employee
end

app/controllers/login_histories_controller.rb
class LoginHistoriesController < ApplicationController
  # GET /login_histories
  # GET /login_histories.json
  def index
    @count_hash = LoginHistory.group(:login).count
    #@login_histories = LoginHistory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @login_histories }
    end
  end

  # GET /login_histories/1
  # GET /login_histories/1.json
  def show
    @login_history = LoginHistory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @login_history }
    end
  end

  # GET /login_histories/new
  # GET /login_histories/new.json
  def new
    @login_history = LoginHistory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @login_history }
    end
  end

  # GET /login_histories/1/edit
  def edit
    @login_history = LoginHistory.find(params[:id])
  end

  # POST /login_histories
  # POST /login_histories.json
  def create
    @login_history = LoginHistory.new(params[:login_history])

    respond_to do |format|
      if @login_history.save
        format.html { redirect_to @login_history, notice: 'Login history was successfully created.' }
        format.json { render json: @login_history, status: :created, location: @login_history }
      else
        format.html { render action: "new" }
        format.json { render json: @login_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /login_histories/1
  # PUT /login_histories/1.json
  def update
    @login_history = LoginHistory.find(params[:id])

    respond_to do |format|
      if @login_history.update_attributes(params[:login_history])
        format.html { redirect_to @login_history, notice: 'Login history was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @login_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /login_histories/1
  # DELETE /login_histories/1.json
  def destroy
    @login_history = LoginHistory.find(params[:id])
    @login_history.destroy

    respond_to do |format|
      format.html { redirect_to login_histories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/login_histories_helper.rb
module LoginHistoriesHelper
end

app/views/login_histories/_form.html.erb
<%= form_for(@login_history) do |f| %>
  <% if @login_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login_history.errors.count, "error") %> prohibited this login_history from being saved:</h2>

      <ul>
      <% @login_history.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/login_histories/edit.html.erb
<h1>Editing login_history</h1>

<%= render 'form' %>

<%= link_to 'Show', @login_history %> |
<%= link_to 'Back', login_histories_path %>

app/views/login_histories/index.html.erb
<h1>Listing login_histories</h1>

<table>
  <tr>
    <th>User</th>
    <th>Last Login</th>
    <th>Count</th>
  </tr>

<% @count_hash.each_key do |k| %>


  <tr>
		<td><%= k %></td>
		<td><%= LoginHistory.where("login = ? ", k).order("created_at desc").limit(1).first.name %></td>
		<td><%= @count_hash[k] %></td>
    
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Login history', new_login_history_path %>

app/views/login_histories/new.html.erb
<h1>New login_history</h1>

<%= render 'form' %>

<%= link_to 'Back', login_histories_path %>

app/views/login_histories/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_login_history_path(@login_history) %> |
<%= link_to 'Back', login_histories_path %>